### ISSUE TITLE
Feedback on palindrome and string algorithms

### ISSUE THREAD

**Issue by Anisha7** [escofresco/makeschool_cs13_core_ds#2]
**Palindromes**
Syntax error on line 25 breaks your code, fix this to pass all tests. Otherwise, good job on your palindrome methods. Challenge yourself by implementing anagram generating function and writing new tests.

**Strings**
Great work on implementing all of the methods. Additionally, work on refactoring (does find_all_indices have code you have already written for another method?) for full credit. To further improve your code, think about how you could optimize find_index to be faster (Could you make it O(N)?).

**Comment by escofresco** [comment]
Anisha, the walrus operator on line 25 was added to python 3.8. Make sure you are using the latest version of python!
