### ISSUE TITLE
CS 1.3 Submission 3 and 4 Review

### ISSUE THREAD

**Issue by SWHarrison** [escofresco/makeschool_cs13_core_ds#3]
Linked List: Works as expected, nice work!

Queues: All tests pass. I recommend keeping the queue methods inside of the queue class to keep code clean and compartmentalized. I also recommend using the delete method to ensure that the old head node is properly unlinked from the rest of the list.

Stacks: Looks good!

Hash tables: Looks good!

**Comment by escofresco** [comment]
Thanks
